<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin.proto

namespace Graphqlc\Compiler;

if (false) {
    /**
     * This class is deprecated. Use Graphqlc\Compiler\CodeGeneratorResponse\File instead.
     * @deprecated
     */
    class CodeGeneratorResponse_File {}
}
class_exists(CodeGeneratorResponse\File::class);
@trigger_error('Graphqlc\Compiler\CodeGeneratorResponse_File is deprecated and will be removed in the next major release. Use Graphqlc\Compiler\CodeGeneratorResponse\File instead', E_USER_DEPRECATED);

