<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graphqlc/compiler/plugin.proto

namespace Graphqlc\Compiler;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * An encoded CodeGeneratorRequest is written to the plugins stdin.
 *
 * Generated from protobuf message <code>graphqlc.compiler.CodeGeneratorRequest</code>
 */
class CodeGeneratorRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The .graphql files that were explicitly listed on the command-line.
     * The code generator should generate code only for these files.
     * Each files descriptor will be included in graphql_file, defined below.
     *
     * Generated from protobuf field <code>repeated string file_to_generate = 1;</code>
     */
    private $file_to_generate;
    /**
     * Generated from protobuf field <code>string parameter = 2;</code>
     */
    private $parameter = '';
    /**
     * FileDescriptorGraphql for all files in files_to_generate.
     *
     * Generated from protobuf field <code>repeated .graphqlc.FileDescriptorGraphql graphql_file = 15;</code>
     */
    private $graphql_file;
    /**
     * The version number of graphql compiler
     *
     * Generated from protobuf field <code>.graphqlc.compiler.Version compiler_version = 3;</code>
     */
    private $compiler_version = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $file_to_generate
     *           The .graphql files that were explicitly listed on the command-line.
     *           The code generator should generate code only for these files.
     *           Each files descriptor will be included in graphql_file, defined below.
     *     @type string $parameter
     *     @type \Graphqlc\FileDescriptorGraphql[]|\Google\Protobuf\Internal\RepeatedField $graphql_file
     *           FileDescriptorGraphql for all files in files_to_generate.
     *     @type \Graphqlc\Compiler\Version $compiler_version
     *           The version number of graphql compiler
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Graphqlc\Compiler\Plugin::initOnce();
        parent::__construct($data);
    }

    /**
     * The .graphql files that were explicitly listed on the command-line.
     * The code generator should generate code only for these files.
     * Each files descriptor will be included in graphql_file, defined below.
     *
     * Generated from protobuf field <code>repeated string file_to_generate = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFileToGenerate()
    {
        return $this->file_to_generate;
    }

    /**
     * The .graphql files that were explicitly listed on the command-line.
     * The code generator should generate code only for these files.
     * Each files descriptor will be included in graphql_file, defined below.
     *
     * Generated from protobuf field <code>repeated string file_to_generate = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFileToGenerate($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->file_to_generate = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string parameter = 2;</code>
     * @return string
     */
    public function getParameter()
    {
        return $this->parameter;
    }

    /**
     * Generated from protobuf field <code>string parameter = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setParameter($var)
    {
        GPBUtil::checkString($var, True);
        $this->parameter = $var;

        return $this;
    }

    /**
     * FileDescriptorGraphql for all files in files_to_generate.
     *
     * Generated from protobuf field <code>repeated .graphqlc.FileDescriptorGraphql graphql_file = 15;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGraphqlFile()
    {
        return $this->graphql_file;
    }

    /**
     * FileDescriptorGraphql for all files in files_to_generate.
     *
     * Generated from protobuf field <code>repeated .graphqlc.FileDescriptorGraphql graphql_file = 15;</code>
     * @param \Graphqlc\FileDescriptorGraphql[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGraphqlFile($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Graphqlc\FileDescriptorGraphql::class);
        $this->graphql_file = $arr;

        return $this;
    }

    /**
     * The version number of graphql compiler
     *
     * Generated from protobuf field <code>.graphqlc.compiler.Version compiler_version = 3;</code>
     * @return \Graphqlc\Compiler\Version
     */
    public function getCompilerVersion()
    {
        return $this->compiler_version;
    }

    /**
     * The version number of graphql compiler
     *
     * Generated from protobuf field <code>.graphqlc.compiler.Version compiler_version = 3;</code>
     * @param \Graphqlc\Compiler\Version $var
     * @return $this
     */
    public function setCompilerVersion($var)
    {
        GPBUtil::checkMessage($var, \Graphqlc\Compiler\Version::class);
        $this->compiler_version = $var;

        return $this;
    }

}

