<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graphqlc/descriptor.proto

namespace Graphqlc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>graphqlc.DirectiveDefinitionDescriptorProto</code>
 */
class DirectiveDefinitionDescriptorProto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string description = 1;</code>
     */
    private $description = '';
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>repeated .graphqlc.InputValueDefinitionDescriptorProto arguments = 3;</code>
     */
    private $arguments;
    /**
     * Generated from protobuf field <code>repeated .graphqlc.DirectiveLocationDescriptorProto locations = 4;</code>
     */
    private $locations;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $description
     *     @type string $name
     *     @type \Graphqlc\InputValueDefinitionDescriptorProto[]|\Google\Protobuf\Internal\RepeatedField $arguments
     *     @type \Graphqlc\DirectiveLocationDescriptorProto[]|\Google\Protobuf\Internal\RepeatedField $locations
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Graphqlc\Descriptor::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string description = 1;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .graphqlc.InputValueDefinitionDescriptorProto arguments = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getArguments()
    {
        return $this->arguments;
    }

    /**
     * Generated from protobuf field <code>repeated .graphqlc.InputValueDefinitionDescriptorProto arguments = 3;</code>
     * @param \Graphqlc\InputValueDefinitionDescriptorProto[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setArguments($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Graphqlc\InputValueDefinitionDescriptorProto::class);
        $this->arguments = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .graphqlc.DirectiveLocationDescriptorProto locations = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLocations()
    {
        return $this->locations;
    }

    /**
     * Generated from protobuf field <code>repeated .graphqlc.DirectiveLocationDescriptorProto locations = 4;</code>
     * @param \Graphqlc\DirectiveLocationDescriptorProto[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLocations($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Graphqlc\DirectiveLocationDescriptorProto::class);
        $this->locations = $arr;

        return $this;
    }

}

