<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graphqlc/descriptor.proto

namespace Graphqlc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>graphqlc.EnumValueDefinitionDescription</code>
 */
class EnumValueDefinitionDescription extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string description = 1;</code>
     */
    private $description = '';
    /**
     * Generated from protobuf field <code>string value = 2;</code>
     */
    private $value = '';
    /**
     * Generated from protobuf field <code>repeated .graphqlc.DirectiveDescriptorProto directives = 3;</code>
     */
    private $directives;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $description
     *     @type string $value
     *     @type \Graphqlc\DirectiveDescriptorProto[]|\Google\Protobuf\Internal\RepeatedField $directives
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Graphqlc\Descriptor::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string description = 1;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string value = 2;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>string value = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .graphqlc.DirectiveDescriptorProto directives = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDirectives()
    {
        return $this->directives;
    }

    /**
     * Generated from protobuf field <code>repeated .graphqlc.DirectiveDescriptorProto directives = 3;</code>
     * @param \Graphqlc\DirectiveDescriptorProto[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDirectives($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Graphqlc\DirectiveDescriptorProto::class);
        $this->directives = $arr;

        return $this;
    }

}

