<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graphqlc/descriptor.proto

namespace Graphqlc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The protocol compiler can output a FileDescriptorSet containing the
 * .graphql file it parses.
 *
 * Generated from protobuf message <code>graphqlc.FileDescriptorSet</code>
 */
class FileDescriptorSet extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .graphqlc.FileDescriptorGraphql file = 1;</code>
     */
    private $file;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Graphqlc\FileDescriptorGraphql[]|\Google\Protobuf\Internal\RepeatedField $file
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Graphqlc\Descriptor::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .graphqlc.FileDescriptorGraphql file = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFile()
    {
        return $this->file;
    }

    /**
     * Generated from protobuf field <code>repeated .graphqlc.FileDescriptorGraphql file = 1;</code>
     * @param \Graphqlc\FileDescriptorGraphql[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFile($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Graphqlc\FileDescriptorGraphql::class);
        $this->file = $arr;

        return $this;
    }

}

