<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graphqlc/descriptor.proto

namespace Graphqlc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Describe a complete .graphql file
 *
 * Generated from protobuf message <code>graphqlc.FileDescriptorGraphql</code>
 */
class FileDescriptorGraphql extends \Google\Protobuf\Internal\Message
{
    /**
     * file name, relative to root of source tree
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    private $name = '';
    /**
     * All top-level definitions in this file.
     *
     * Generated from protobuf field <code>.graphqlc.SchemaDescriptorProto schema = 2;</code>
     */
    private $schema = null;
    /**
     * Generated from protobuf field <code>repeated .graphqlc.TypeSystemExtensionDescriptorProto type_extensions = 10;</code>
     */
    private $type_extensions;
    /**
     * Generated from protobuf field <code>repeated .graphqlc.DirectiveDefinitionDescriptorProto directives = 9;</code>
     */
    private $directives;
    /**
     * Generated from protobuf field <code>repeated .graphqlc.ScalarTypeDefinitionDescriptorProto scalars = 3;</code>
     */
    private $scalars;
    /**
     * Generated from protobuf field <code>repeated .graphqlc.ObjectTypeDefinitionDescriptorProto objects = 4;</code>
     */
    private $objects;
    /**
     * Generated from protobuf field <code>repeated .graphqlc.InterfaceTypeDefinitionDescriptorProto interfaces = 5;</code>
     */
    private $interfaces;
    /**
     * Generated from protobuf field <code>repeated .graphqlc.UnionTypeDefinitionDescriptorProto unions = 6;</code>
     */
    private $unions;
    /**
     * Generated from protobuf field <code>repeated .graphqlc.EnumTypeDefinitionDescriptorProto enums = 7;</code>
     */
    private $enums;
    /**
     * Generated from protobuf field <code>repeated .graphqlc.InputObjectTypeDefinitionDescriptorProto input_objects = 8;</code>
     */
    private $input_objects;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           file name, relative to root of source tree
     *     @type \Graphqlc\SchemaDescriptorProto $schema
     *           All top-level definitions in this file.
     *     @type \Graphqlc\TypeSystemExtensionDescriptorProto[]|\Google\Protobuf\Internal\RepeatedField $type_extensions
     *     @type \Graphqlc\DirectiveDefinitionDescriptorProto[]|\Google\Protobuf\Internal\RepeatedField $directives
     *     @type \Graphqlc\ScalarTypeDefinitionDescriptorProto[]|\Google\Protobuf\Internal\RepeatedField $scalars
     *     @type \Graphqlc\ObjectTypeDefinitionDescriptorProto[]|\Google\Protobuf\Internal\RepeatedField $objects
     *     @type \Graphqlc\InterfaceTypeDefinitionDescriptorProto[]|\Google\Protobuf\Internal\RepeatedField $interfaces
     *     @type \Graphqlc\UnionTypeDefinitionDescriptorProto[]|\Google\Protobuf\Internal\RepeatedField $unions
     *     @type \Graphqlc\EnumTypeDefinitionDescriptorProto[]|\Google\Protobuf\Internal\RepeatedField $enums
     *     @type \Graphqlc\InputObjectTypeDefinitionDescriptorProto[]|\Google\Protobuf\Internal\RepeatedField $input_objects
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Graphqlc\Descriptor::initOnce();
        parent::__construct($data);
    }

    /**
     * file name, relative to root of source tree
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * file name, relative to root of source tree
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * All top-level definitions in this file.
     *
     * Generated from protobuf field <code>.graphqlc.SchemaDescriptorProto schema = 2;</code>
     * @return \Graphqlc\SchemaDescriptorProto
     */
    public function getSchema()
    {
        return $this->schema;
    }

    /**
     * All top-level definitions in this file.
     *
     * Generated from protobuf field <code>.graphqlc.SchemaDescriptorProto schema = 2;</code>
     * @param \Graphqlc\SchemaDescriptorProto $var
     * @return $this
     */
    public function setSchema($var)
    {
        GPBUtil::checkMessage($var, \Graphqlc\SchemaDescriptorProto::class);
        $this->schema = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .graphqlc.TypeSystemExtensionDescriptorProto type_extensions = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTypeExtensions()
    {
        return $this->type_extensions;
    }

    /**
     * Generated from protobuf field <code>repeated .graphqlc.TypeSystemExtensionDescriptorProto type_extensions = 10;</code>
     * @param \Graphqlc\TypeSystemExtensionDescriptorProto[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTypeExtensions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Graphqlc\TypeSystemExtensionDescriptorProto::class);
        $this->type_extensions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .graphqlc.DirectiveDefinitionDescriptorProto directives = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDirectives()
    {
        return $this->directives;
    }

    /**
     * Generated from protobuf field <code>repeated .graphqlc.DirectiveDefinitionDescriptorProto directives = 9;</code>
     * @param \Graphqlc\DirectiveDefinitionDescriptorProto[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDirectives($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Graphqlc\DirectiveDefinitionDescriptorProto::class);
        $this->directives = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .graphqlc.ScalarTypeDefinitionDescriptorProto scalars = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getScalars()
    {
        return $this->scalars;
    }

    /**
     * Generated from protobuf field <code>repeated .graphqlc.ScalarTypeDefinitionDescriptorProto scalars = 3;</code>
     * @param \Graphqlc\ScalarTypeDefinitionDescriptorProto[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setScalars($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Graphqlc\ScalarTypeDefinitionDescriptorProto::class);
        $this->scalars = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .graphqlc.ObjectTypeDefinitionDescriptorProto objects = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getObjects()
    {
        return $this->objects;
    }

    /**
     * Generated from protobuf field <code>repeated .graphqlc.ObjectTypeDefinitionDescriptorProto objects = 4;</code>
     * @param \Graphqlc\ObjectTypeDefinitionDescriptorProto[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setObjects($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Graphqlc\ObjectTypeDefinitionDescriptorProto::class);
        $this->objects = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .graphqlc.InterfaceTypeDefinitionDescriptorProto interfaces = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getInterfaces()
    {
        return $this->interfaces;
    }

    /**
     * Generated from protobuf field <code>repeated .graphqlc.InterfaceTypeDefinitionDescriptorProto interfaces = 5;</code>
     * @param \Graphqlc\InterfaceTypeDefinitionDescriptorProto[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setInterfaces($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Graphqlc\InterfaceTypeDefinitionDescriptorProto::class);
        $this->interfaces = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .graphqlc.UnionTypeDefinitionDescriptorProto unions = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUnions()
    {
        return $this->unions;
    }

    /**
     * Generated from protobuf field <code>repeated .graphqlc.UnionTypeDefinitionDescriptorProto unions = 6;</code>
     * @param \Graphqlc\UnionTypeDefinitionDescriptorProto[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUnions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Graphqlc\UnionTypeDefinitionDescriptorProto::class);
        $this->unions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .graphqlc.EnumTypeDefinitionDescriptorProto enums = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEnums()
    {
        return $this->enums;
    }

    /**
     * Generated from protobuf field <code>repeated .graphqlc.EnumTypeDefinitionDescriptorProto enums = 7;</code>
     * @param \Graphqlc\EnumTypeDefinitionDescriptorProto[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEnums($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Graphqlc\EnumTypeDefinitionDescriptorProto::class);
        $this->enums = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .graphqlc.InputObjectTypeDefinitionDescriptorProto input_objects = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getInputObjects()
    {
        return $this->input_objects;
    }

    /**
     * Generated from protobuf field <code>repeated .graphqlc.InputObjectTypeDefinitionDescriptorProto input_objects = 8;</code>
     * @param \Graphqlc\InputObjectTypeDefinitionDescriptorProto[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setInputObjects($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Graphqlc\InputObjectTypeDefinitionDescriptorProto::class);
        $this->input_objects = $arr;

        return $this;
    }

}

