<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graphqlc/descriptor.proto

namespace Graphqlc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>graphqlc.InputValueDefinitionDescriptorProto</code>
 */
class InputValueDefinitionDescriptorProto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string description = 1;</code>
     */
    private $description = '';
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>.graphqlc.TypeDescriptorProto type = 3;</code>
     */
    private $type = null;
    /**
     * Generated from protobuf field <code>.graphqlc.ValueDescriptorProto default_value = 4;</code>
     */
    private $default_value = null;
    /**
     * Generated from protobuf field <code>repeated .graphqlc.DirectiveDescriptorProto directives = 5;</code>
     */
    private $directives;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $description
     *     @type string $name
     *     @type \Graphqlc\TypeDescriptorProto $type
     *     @type \Graphqlc\ValueDescriptorProto $default_value
     *     @type \Graphqlc\DirectiveDescriptorProto[]|\Google\Protobuf\Internal\RepeatedField $directives
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Graphqlc\Descriptor::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string description = 1;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.graphqlc.TypeDescriptorProto type = 3;</code>
     * @return \Graphqlc\TypeDescriptorProto
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.graphqlc.TypeDescriptorProto type = 3;</code>
     * @param \Graphqlc\TypeDescriptorProto $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkMessage($var, \Graphqlc\TypeDescriptorProto::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.graphqlc.ValueDescriptorProto default_value = 4;</code>
     * @return \Graphqlc\ValueDescriptorProto
     */
    public function getDefaultValue()
    {
        return $this->default_value;
    }

    /**
     * Generated from protobuf field <code>.graphqlc.ValueDescriptorProto default_value = 4;</code>
     * @param \Graphqlc\ValueDescriptorProto $var
     * @return $this
     */
    public function setDefaultValue($var)
    {
        GPBUtil::checkMessage($var, \Graphqlc\ValueDescriptorProto::class);
        $this->default_value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .graphqlc.DirectiveDescriptorProto directives = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDirectives()
    {
        return $this->directives;
    }

    /**
     * Generated from protobuf field <code>repeated .graphqlc.DirectiveDescriptorProto directives = 5;</code>
     * @param \Graphqlc\DirectiveDescriptorProto[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDirectives($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Graphqlc\DirectiveDescriptorProto::class);
        $this->directives = $arr;

        return $this;
    }

}

