<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graphqlc/descriptor.proto

namespace Graphqlc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>graphqlc.ListTypeDescriptorProto</code>
 */
class ListTypeDescriptorProto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.graphqlc.TypeDescriptorProto type = 1;</code>
     */
    private $type = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Graphqlc\TypeDescriptorProto $type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Graphqlc\Descriptor::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.graphqlc.TypeDescriptorProto type = 1;</code>
     * @return \Graphqlc\TypeDescriptorProto
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.graphqlc.TypeDescriptorProto type = 1;</code>
     * @param \Graphqlc\TypeDescriptorProto $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkMessage($var, \Graphqlc\TypeDescriptorProto::class);
        $this->type = $var;

        return $this;
    }

}

