<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graphqlc/descriptor.proto

namespace Graphqlc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>graphqlc.ObjectFieldDescriptorProto</code>
 */
class ObjectFieldDescriptorProto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>.graphqlc.ValueDescriptorProto value = 2;</code>
     */
    private $value = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type \Graphqlc\ValueDescriptorProto $value
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Graphqlc\Descriptor::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.graphqlc.ValueDescriptorProto value = 2;</code>
     * @return \Graphqlc\ValueDescriptorProto
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>.graphqlc.ValueDescriptorProto value = 2;</code>
     * @param \Graphqlc\ValueDescriptorProto $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkMessage($var, \Graphqlc\ValueDescriptorProto::class);
        $this->value = $var;

        return $this;
    }

}

