<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graphqlc/descriptor.proto

namespace Graphqlc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>graphqlc.ObjectTypeExtensionDescriptorProto</code>
 */
class ObjectTypeExtensionDescriptorProto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>repeated .graphqlc.InterfaceTypeDefinitionDescriptorProto implements = 3;</code>
     */
    private $implements;
    /**
     * Generated from protobuf field <code>repeated .graphqlc.DirectiveDescriptorProto directives = 4;</code>
     */
    private $directives;
    /**
     * Generated from protobuf field <code>repeated .graphqlc.FieldDefinitionDescriptorProto fields = 5;</code>
     */
    private $fields;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type \Graphqlc\InterfaceTypeDefinitionDescriptorProto[]|\Google\Protobuf\Internal\RepeatedField $implements
     *     @type \Graphqlc\DirectiveDescriptorProto[]|\Google\Protobuf\Internal\RepeatedField $directives
     *     @type \Graphqlc\FieldDefinitionDescriptorProto[]|\Google\Protobuf\Internal\RepeatedField $fields
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Graphqlc\Descriptor::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .graphqlc.InterfaceTypeDefinitionDescriptorProto implements = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getImplements()
    {
        return $this->implements;
    }

    /**
     * Generated from protobuf field <code>repeated .graphqlc.InterfaceTypeDefinitionDescriptorProto implements = 3;</code>
     * @param \Graphqlc\InterfaceTypeDefinitionDescriptorProto[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setImplements($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Graphqlc\InterfaceTypeDefinitionDescriptorProto::class);
        $this->implements = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .graphqlc.DirectiveDescriptorProto directives = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDirectives()
    {
        return $this->directives;
    }

    /**
     * Generated from protobuf field <code>repeated .graphqlc.DirectiveDescriptorProto directives = 4;</code>
     * @param \Graphqlc\DirectiveDescriptorProto[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDirectives($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Graphqlc\DirectiveDescriptorProto::class);
        $this->directives = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .graphqlc.FieldDefinitionDescriptorProto fields = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFields()
    {
        return $this->fields;
    }

    /**
     * Generated from protobuf field <code>repeated .graphqlc.FieldDefinitionDescriptorProto fields = 5;</code>
     * @param \Graphqlc\FieldDefinitionDescriptorProto[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFields($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Graphqlc\FieldDefinitionDescriptorProto::class);
        $this->fields = $arr;

        return $this;
    }

}

