<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graphqlc/descriptor.proto

namespace Graphqlc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>graphqlc.SchemaExtensionDescriptorProto</code>
 */
class SchemaExtensionDescriptorProto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .graphqlc.DirectiveDescriptorProto directives = 1;</code>
     */
    private $directives;
    /**
     * Generated from protobuf field <code>repeated .graphqlc.NamedTypeDescriptorProto operation_type_definitions = 2;</code>
     */
    private $operation_type_definitions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Graphqlc\DirectiveDescriptorProto[]|\Google\Protobuf\Internal\RepeatedField $directives
     *     @type \Graphqlc\NamedTypeDescriptorProto[]|\Google\Protobuf\Internal\RepeatedField $operation_type_definitions
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Graphqlc\Descriptor::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .graphqlc.DirectiveDescriptorProto directives = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDirectives()
    {
        return $this->directives;
    }

    /**
     * Generated from protobuf field <code>repeated .graphqlc.DirectiveDescriptorProto directives = 1;</code>
     * @param \Graphqlc\DirectiveDescriptorProto[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDirectives($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Graphqlc\DirectiveDescriptorProto::class);
        $this->directives = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .graphqlc.NamedTypeDescriptorProto operation_type_definitions = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOperationTypeDefinitions()
    {
        return $this->operation_type_definitions;
    }

    /**
     * Generated from protobuf field <code>repeated .graphqlc.NamedTypeDescriptorProto operation_type_definitions = 2;</code>
     * @param \Graphqlc\NamedTypeDescriptorProto[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOperationTypeDefinitions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Graphqlc\NamedTypeDescriptorProto::class);
        $this->operation_type_definitions = $arr;

        return $this;
    }

}

