<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graphqlc/descriptor.proto

namespace Graphqlc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>graphqlc.TypeDescriptorProto</code>
 */
class TypeDescriptorProto extends \Google\Protobuf\Internal\Message
{
    protected $type;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Graphqlc\NamedTypeDescriptorProto $named_type
     *     @type \Graphqlc\ListTypeDescriptorProto $list_type
     *     @type \Graphqlc\NonNullTypeDescriptorProto $non_null_type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Graphqlc\Descriptor::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.graphqlc.NamedTypeDescriptorProto named_type = 1;</code>
     * @return \Graphqlc\NamedTypeDescriptorProto
     */
    public function getNamedType()
    {
        return $this->readOneof(1);
    }

    /**
     * Generated from protobuf field <code>.graphqlc.NamedTypeDescriptorProto named_type = 1;</code>
     * @param \Graphqlc\NamedTypeDescriptorProto $var
     * @return $this
     */
    public function setNamedType($var)
    {
        GPBUtil::checkMessage($var, \Graphqlc\NamedTypeDescriptorProto::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.graphqlc.ListTypeDescriptorProto list_type = 2;</code>
     * @return \Graphqlc\ListTypeDescriptorProto
     */
    public function getListType()
    {
        return $this->readOneof(2);
    }

    /**
     * Generated from protobuf field <code>.graphqlc.ListTypeDescriptorProto list_type = 2;</code>
     * @param \Graphqlc\ListTypeDescriptorProto $var
     * @return $this
     */
    public function setListType($var)
    {
        GPBUtil::checkMessage($var, \Graphqlc\ListTypeDescriptorProto::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.graphqlc.NonNullTypeDescriptorProto non_null_type = 3;</code>
     * @return \Graphqlc\NonNullTypeDescriptorProto
     */
    public function getNonNullType()
    {
        return $this->readOneof(3);
    }

    /**
     * Generated from protobuf field <code>.graphqlc.NonNullTypeDescriptorProto non_null_type = 3;</code>
     * @param \Graphqlc\NonNullTypeDescriptorProto $var
     * @return $this
     */
    public function setNonNullType($var)
    {
        GPBUtil::checkMessage($var, \Graphqlc\NonNullTypeDescriptorProto::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getType()
    {
        return $this->whichOneof("type");
    }

}

