<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graphqlc/descriptor.proto

namespace Graphqlc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>graphqlc.TypeExtensionDescriptorProto</code>
 */
class TypeExtensionDescriptorProto extends \Google\Protobuf\Internal\Message
{
    protected $type_extension;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Graphqlc\ScalarTypeExtensionDescriptorProto $scalar_type_extension
     *     @type \Graphqlc\ObjectTypeExtensionDescriptorProto $object_type_extension
     *     @type \Graphqlc\InterfaceTypeExtensionDescriptorProto $interface_type_extension
     *     @type \Graphqlc\UnionTypeExtensionDefinitionDescriptorProto $union_type_extension
     *     @type \Graphqlc\EnumTypeExtensionDefinitionDescriptorProto $enum_type_extions
     *     @type \Graphqlc\InputObjectTypeExtensionDefinitionDescriptorProto $input_object_type_extension
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Graphqlc\Descriptor::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.graphqlc.ScalarTypeExtensionDescriptorProto scalar_type_extension = 1;</code>
     * @return \Graphqlc\ScalarTypeExtensionDescriptorProto
     */
    public function getScalarTypeExtension()
    {
        return $this->readOneof(1);
    }

    /**
     * Generated from protobuf field <code>.graphqlc.ScalarTypeExtensionDescriptorProto scalar_type_extension = 1;</code>
     * @param \Graphqlc\ScalarTypeExtensionDescriptorProto $var
     * @return $this
     */
    public function setScalarTypeExtension($var)
    {
        GPBUtil::checkMessage($var, \Graphqlc\ScalarTypeExtensionDescriptorProto::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.graphqlc.ObjectTypeExtensionDescriptorProto object_type_extension = 2;</code>
     * @return \Graphqlc\ObjectTypeExtensionDescriptorProto
     */
    public function getObjectTypeExtension()
    {
        return $this->readOneof(2);
    }

    /**
     * Generated from protobuf field <code>.graphqlc.ObjectTypeExtensionDescriptorProto object_type_extension = 2;</code>
     * @param \Graphqlc\ObjectTypeExtensionDescriptorProto $var
     * @return $this
     */
    public function setObjectTypeExtension($var)
    {
        GPBUtil::checkMessage($var, \Graphqlc\ObjectTypeExtensionDescriptorProto::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.graphqlc.InterfaceTypeExtensionDescriptorProto interface_type_extension = 3;</code>
     * @return \Graphqlc\InterfaceTypeExtensionDescriptorProto
     */
    public function getInterfaceTypeExtension()
    {
        return $this->readOneof(3);
    }

    /**
     * Generated from protobuf field <code>.graphqlc.InterfaceTypeExtensionDescriptorProto interface_type_extension = 3;</code>
     * @param \Graphqlc\InterfaceTypeExtensionDescriptorProto $var
     * @return $this
     */
    public function setInterfaceTypeExtension($var)
    {
        GPBUtil::checkMessage($var, \Graphqlc\InterfaceTypeExtensionDescriptorProto::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.graphqlc.UnionTypeExtensionDefinitionDescriptorProto union_type_extension = 4;</code>
     * @return \Graphqlc\UnionTypeExtensionDefinitionDescriptorProto
     */
    public function getUnionTypeExtension()
    {
        return $this->readOneof(4);
    }

    /**
     * Generated from protobuf field <code>.graphqlc.UnionTypeExtensionDefinitionDescriptorProto union_type_extension = 4;</code>
     * @param \Graphqlc\UnionTypeExtensionDefinitionDescriptorProto $var
     * @return $this
     */
    public function setUnionTypeExtension($var)
    {
        GPBUtil::checkMessage($var, \Graphqlc\UnionTypeExtensionDefinitionDescriptorProto::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.graphqlc.EnumTypeExtensionDefinitionDescriptorProto enum_type_extions = 5;</code>
     * @return \Graphqlc\EnumTypeExtensionDefinitionDescriptorProto
     */
    public function getEnumTypeExtions()
    {
        return $this->readOneof(5);
    }

    /**
     * Generated from protobuf field <code>.graphqlc.EnumTypeExtensionDefinitionDescriptorProto enum_type_extions = 5;</code>
     * @param \Graphqlc\EnumTypeExtensionDefinitionDescriptorProto $var
     * @return $this
     */
    public function setEnumTypeExtions($var)
    {
        GPBUtil::checkMessage($var, \Graphqlc\EnumTypeExtensionDefinitionDescriptorProto::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.graphqlc.InputObjectTypeExtensionDefinitionDescriptorProto input_object_type_extension = 6;</code>
     * @return \Graphqlc\InputObjectTypeExtensionDefinitionDescriptorProto
     */
    public function getInputObjectTypeExtension()
    {
        return $this->readOneof(6);
    }

    /**
     * Generated from protobuf field <code>.graphqlc.InputObjectTypeExtensionDefinitionDescriptorProto input_object_type_extension = 6;</code>
     * @param \Graphqlc\InputObjectTypeExtensionDefinitionDescriptorProto $var
     * @return $this
     */
    public function setInputObjectTypeExtension($var)
    {
        GPBUtil::checkMessage($var, \Graphqlc\InputObjectTypeExtensionDefinitionDescriptorProto::class);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getTypeExtension()
    {
        return $this->whichOneof("type_extension");
    }

}

