<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graphqlc/descriptor.proto

namespace Graphqlc;

use UnexpectedValueException;

/**
 * Protobuf type <code>graphqlc.TypeSystemDirectiveLocation</code>
 */
class TypeSystemDirectiveLocation
{
    /**
     * Generated from protobuf enum <code>SCHEMA = 0;</code>
     */
    const SCHEMA = 0;
    /**
     * Generated from protobuf enum <code>SCALAR = 1;</code>
     */
    const SCALAR = 1;
    /**
     * Generated from protobuf enum <code>OBJECT = 2;</code>
     */
    const OBJECT = 2;
    /**
     * Generated from protobuf enum <code>FIELD_DEFINITION = 3;</code>
     */
    const FIELD_DEFINITION = 3;
    /**
     * Generated from protobuf enum <code>ARGUMENT_DEFINITION = 4;</code>
     */
    const ARGUMENT_DEFINITION = 4;
    /**
     * Generated from protobuf enum <code>INTERFACE = 5;</code>
     */
    const PBINTERFACE = 5;
    /**
     * Generated from protobuf enum <code>UNION = 6;</code>
     */
    const UNION = 6;
    /**
     * Generated from protobuf enum <code>ENUM = 7;</code>
     */
    const ENUM = 7;
    /**
     * Generated from protobuf enum <code>ENUM_VALUE = 8;</code>
     */
    const ENUM_VALUE = 8;
    /**
     * Generated from protobuf enum <code>INPUT_OBJECT = 9;</code>
     */
    const INPUT_OBJECT = 9;
    /**
     * Generated from protobuf enum <code>INPUT_FIELD_DEFINITION = 10;</code>
     */
    const INPUT_FIELD_DEFINITION = 10;

    private static $valueToName = [
        self::SCHEMA => 'SCHEMA',
        self::SCALAR => 'SCALAR',
        self::OBJECT => 'OBJECT',
        self::FIELD_DEFINITION => 'FIELD_DEFINITION',
        self::ARGUMENT_DEFINITION => 'ARGUMENT_DEFINITION',
        self::PBINTERFACE => 'PBINTERFACE',
        self::UNION => 'UNION',
        self::ENUM => 'ENUM',
        self::ENUM_VALUE => 'ENUM_VALUE',
        self::INPUT_OBJECT => 'INPUT_OBJECT',
        self::INPUT_FIELD_DEFINITION => 'INPUT_FIELD_DEFINITION',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

