<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graphqlc/descriptor.proto

namespace Graphqlc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>graphqlc.UnionTypeExtensionDefinitionDescriptorProto</code>
 */
class UnionTypeExtensionDefinitionDescriptorProto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>repeated .graphqlc.DirectiveDescriptorProto directives = 2;</code>
     */
    private $directives;
    /**
     * Generated from protobuf field <code>repeated .graphqlc.NamedTypeDescriptorProto member_types = 3;</code>
     */
    private $member_types;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type \Graphqlc\DirectiveDescriptorProto[]|\Google\Protobuf\Internal\RepeatedField $directives
     *     @type \Graphqlc\NamedTypeDescriptorProto[]|\Google\Protobuf\Internal\RepeatedField $member_types
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Graphqlc\Descriptor::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .graphqlc.DirectiveDescriptorProto directives = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDirectives()
    {
        return $this->directives;
    }

    /**
     * Generated from protobuf field <code>repeated .graphqlc.DirectiveDescriptorProto directives = 2;</code>
     * @param \Graphqlc\DirectiveDescriptorProto[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDirectives($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Graphqlc\DirectiveDescriptorProto::class);
        $this->directives = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .graphqlc.NamedTypeDescriptorProto member_types = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMemberTypes()
    {
        return $this->member_types;
    }

    /**
     * Generated from protobuf field <code>repeated .graphqlc.NamedTypeDescriptorProto member_types = 3;</code>
     * @param \Graphqlc\NamedTypeDescriptorProto[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMemberTypes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Graphqlc\NamedTypeDescriptorProto::class);
        $this->member_types = $arr;

        return $this;
    }

}

