<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graphqlc/descriptor.proto

namespace Graphqlc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>graphqlc.ValueDescriptorProto</code>
 */
class ValueDescriptorProto extends \Google\Protobuf\Internal\Message
{
    protected $value;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Graphqlc\VariableDescriptorProto $variable_value
     *     @type int $int_value
     *     @type float $float_value
     *     @type bool $boolean_value
     *     @type string $string_value
     *     @type \Graphqlc\NullValueDescriptorProto $null_value
     *     @type \Graphqlc\EnumValueDescriptorProto $enum_value
     *     @type \Graphqlc\ListValueDescriptorProto $list_value
     *     @type \Graphqlc\ObjectValueDescriptorProto $object_value
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Graphqlc\Descriptor::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.graphqlc.VariableDescriptorProto variable_value = 2;</code>
     * @return \Graphqlc\VariableDescriptorProto
     */
    public function getVariableValue()
    {
        return $this->readOneof(2);
    }

    /**
     * Generated from protobuf field <code>.graphqlc.VariableDescriptorProto variable_value = 2;</code>
     * @param \Graphqlc\VariableDescriptorProto $var
     * @return $this
     */
    public function setVariableValue($var)
    {
        GPBUtil::checkMessage($var, \Graphqlc\VariableDescriptorProto::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 int_value = 3;</code>
     * @return int
     */
    public function getIntValue()
    {
        return $this->readOneof(3);
    }

    /**
     * Generated from protobuf field <code>int32 int_value = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setIntValue($var)
    {
        GPBUtil::checkInt32($var);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>float float_value = 4;</code>
     * @return float
     */
    public function getFloatValue()
    {
        return $this->readOneof(4);
    }

    /**
     * Generated from protobuf field <code>float float_value = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setFloatValue($var)
    {
        GPBUtil::checkFloat($var);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool boolean_value = 5;</code>
     * @return bool
     */
    public function getBooleanValue()
    {
        return $this->readOneof(5);
    }

    /**
     * Generated from protobuf field <code>bool boolean_value = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setBooleanValue($var)
    {
        GPBUtil::checkBool($var);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string string_value = 6;</code>
     * @return string
     */
    public function getStringValue()
    {
        return $this->readOneof(6);
    }

    /**
     * Generated from protobuf field <code>string string_value = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setStringValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.graphqlc.NullValueDescriptorProto null_value = 7;</code>
     * @return \Graphqlc\NullValueDescriptorProto
     */
    public function getNullValue()
    {
        return $this->readOneof(7);
    }

    /**
     * Generated from protobuf field <code>.graphqlc.NullValueDescriptorProto null_value = 7;</code>
     * @param \Graphqlc\NullValueDescriptorProto $var
     * @return $this
     */
    public function setNullValue($var)
    {
        GPBUtil::checkMessage($var, \Graphqlc\NullValueDescriptorProto::class);
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.graphqlc.EnumValueDescriptorProto enum_value = 8;</code>
     * @return \Graphqlc\EnumValueDescriptorProto
     */
    public function getEnumValue()
    {
        return $this->readOneof(8);
    }

    /**
     * Generated from protobuf field <code>.graphqlc.EnumValueDescriptorProto enum_value = 8;</code>
     * @param \Graphqlc\EnumValueDescriptorProto $var
     * @return $this
     */
    public function setEnumValue($var)
    {
        GPBUtil::checkMessage($var, \Graphqlc\EnumValueDescriptorProto::class);
        $this->writeOneof(8, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.graphqlc.ListValueDescriptorProto list_value = 9;</code>
     * @return \Graphqlc\ListValueDescriptorProto
     */
    public function getListValue()
    {
        return $this->readOneof(9);
    }

    /**
     * Generated from protobuf field <code>.graphqlc.ListValueDescriptorProto list_value = 9;</code>
     * @param \Graphqlc\ListValueDescriptorProto $var
     * @return $this
     */
    public function setListValue($var)
    {
        GPBUtil::checkMessage($var, \Graphqlc\ListValueDescriptorProto::class);
        $this->writeOneof(9, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.graphqlc.ObjectValueDescriptorProto object_value = 10;</code>
     * @return \Graphqlc\ObjectValueDescriptorProto
     */
    public function getObjectValue()
    {
        return $this->readOneof(10);
    }

    /**
     * Generated from protobuf field <code>.graphqlc.ObjectValueDescriptorProto object_value = 10;</code>
     * @param \Graphqlc\ObjectValueDescriptorProto $var
     * @return $this
     */
    public function setObjectValue($var)
    {
        GPBUtil::checkMessage($var, \Graphqlc\ObjectValueDescriptorProto::class);
        $this->writeOneof(10, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getValue()
    {
        return $this->whichOneof("value");
    }

}

